fail_fast: false
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.5.0
        hooks:
        - id: debug-statements
        - id: check-docstring-first
        - id: end-of-file-fixer
        - id: check-merge-conflict
        - id: check-json
        - id: check-added-large-files
        - id: check-yaml
        - id: name-tests-test
        - id: requirements-txt-fixer
        - id: trailing-whitespace

    -   repo: https://github.com/myint/autoflake.git
        rev: v2.2.1
        hooks:
        - id: autoflake
          args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable', '--expand-star-imports', '--ignore-init-module-imports']

    -   repo: https://github.com/psf/black
        rev: 23.9.1
        hooks:
        - id: black
          args: [--line-length=140]

    -   repo: https://github.com/asottile/pyupgrade
        rev: v3.15.0
        hooks:
        - id: pyupgrade
          args: [--py36-plus]

    -   repo: https://github.com/PyCQA/flake8
        rev: 6.1.0
        hooks:
        - id: flake8
          args: [--max-line-length=140]

    -   repo: https://github.com/pylint-dev/pylint
        rev: v3.0.1
        hooks:
        - id: pylint
          args: ['--rcfile=.pylintrc']  # Customize pylint arguments if needed

    -   repo: local
        hooks:
        -   id: run-unit-tests
            name: Run unit tests
            entry: bash -c 'RUNNING_UNIT_TESTS=1 LOGLEVEL=debug PYTHONPATH=$(pwd) pytest --cov=./raspirri --cov-report=xml -rA -s -vv tests'
            language: system
            files: '\.py$'
            pass_filenames: false

    -   repo: local
        hooks:
        -   id: check-ut-code-coverage-below-threshold
            name: Checking whether Unit Tests code coverage is below threshold
            entry: bash -c 'RUNNING_UNIT_TESTS=1 LOGLEVEL=debug PYTHONPATH=$(pwd)/raspirri coverage report -m --fail-under=75 --include='raspirri/*' --sort=Cover --skip-empty --omit='raspirri/ble/*' && echo "Unit Tests Code coverage is above 75%!"'
            language: system
            files: '\.py$'
            pass_filenames: false
