# .github/actions/action.yml
name: 'Common Steps'
description: 'Contains common steps for workflows'
runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/common-steps.yml
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
