name: Common Steps

on:
  workflow_call:
    # Introduced 'inputs' to define parameters that can be passed when calling this workflow
    inputs:
      fake-argument:
        description: "Fake argument"
        required: false
        type: string
  push:
    branches:
      - main
      - feature/create_releases

jobs:
  common-job:
    runs-on: ubuntu-latest
    name: Build, Check Code Conventions, Formatting, Linting, run Unit Tests and check UT code coverage on ubuntu-latest x86_64

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        git config --global user.email "mariosk@gmail.com"
        git config --global user.name "Marios Karagiannopoulos"
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt.x86_64  # Adjust based on your project

    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        pre-commit install

    - name: Run pre-commit
      run: pre-commit run --all-files
