name: Precommit

on:
  workflow_call:
    inputs:
      fake-argument:
        description: "Fake argument"
        required: false
        type: string

jobs:
  common-job:
    runs-on: ubuntu-latest
    name: Build, Check Code Conventions, Formatting, Linting, run Unit Tests and check UT code coverage on ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        pre-commit install

    - name: Run pre-commit
      run: |
        pip install -r requirements-dev.txt  # Adjust based on your project
        pre-commit run --all-files

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      env:
        token: 35e7625a-90fe-44e3-aff3-d09c7bb83743
        slug: gardenifi/raspirri_server
