name: Precommit

on:
  workflow_call:
    inputs:
      fake-argument:
        description: "Fake argument"
        required: false
        type: string

jobs:
  common-job:
    runs-on: ubuntu-latest
    name: Build, Check Code Conventions, Formatting, Linting, run Unit Tests and check UT code coverage on ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        pre-commit install

    - name: Run pre-commit
      run: |
        pip install -r requirements-dev.txt  # Adjust based on your project
        pre-commit run --all-files

    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        RUNNING_UNIT_TESTS=1 LOGLEVEL=debug PYTHONPATH=$(pwd) pytest --cov=./raspirri --cov-report=xml

    - name: Upload coverage reports to Codecov
      run: |
        # Replace `linux` below with the appropriate OS
        # Options are `alpine`, `linux`, `macos`, `windows`
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${{ secrets.CODECOV_TOKEN }} -e OS,PYTHON -F tests --gcov-root ./raspirri

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v3.1.0
    #   with:
    #       token: ${{ secrets.CODECOV_TOKEN }}
    #       fail_ci_if_error: true # optional (default = false)
    #       verbose: true # optional (default = false)
    #       files: ./coverage.xml
    #       env_vars: OS,PYTHON
    #       gcov_include: ./raspirri
