name: Release

on:
  pull_request:
    paths:
      - 'CHANGELOG.md'  # Adjust the path to match your specific file or directory
    branches:
      - main

jobs:
  common-steps:
    uses: gardenifi/raspirri_server/.github/workflows/common-steps.yml@main
    with:
      fake-argument: 'fake'

  release:
    needs: common-steps
    runs-on: ubuntu-latest
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          git config --global user.email "mariosk@gmail.com"
          git config --global user.name "Marios Karagiannopoulos"
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt.x86_64  # Adjust based on your project

      - name: Bump version and create release
        run: |
          pip install bump2version
          NEW_VERSION=$(cat CHANGELOG.md | grep "\- Release" | cut -d' ' -f3 | cut -d'v' -f2 | head -1)
          PART=$(cat CHANGELOG.md | grep "\- part" | cut -d' ' -f3 | head -1)
          bump2version --new-version ${NEW_VERSION} ${PART}
          git pull origin main
          git push --follow-tags origin HEAD:main
          git push origin --tags
          NEW_VERSION=${NEW_VERSION} INSTALLATION_PATH=./tmp invoke upload-to-github
