name: Release

on:
  push:
    paths:
      - 'CHANGELOG.md'

jobs:
  pre-commit:
    uses: gardenifi/raspirri_server/.github/workflows/precommit.yml@fix/update-readme
    with:
      fake-argument: 'fake'

  release:
    needs: pre-commit
    runs-on: ubuntu-latest
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Install dependencies
        run: |
          git config --global user.email "mariosk@gmail.com"
          git config --global user.name "Marios Karagiannopoulos"
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r requirements-dev.txt  # Adjust based on your project

      - name: Bump version and create release
        run: |
          pip install bump2version
          NEW_VERSION=$(cat CHANGELOG.md | grep "\- Release" | cut -d' ' -f3 | cut -d'v' -f2 | head -1)
          PART=$(cat CHANGELOG.md | grep "\- part" | cut -d' ' -f3 | head -1)
          bump2version --new-version ${NEW_VERSION} ${PART}
          git push --follow-tags
          git push origin --tags
          NEW_VERSION=${NEW_VERSION} INSTALLATION_PATH=./tmp invoke upload-to-github
