name: Release

on:
  push:
    tags:
      - '*' # Listen for all tag pushes

jobs:
  pre-commit:
    uses: gardenifi/raspirri_server/.github/workflows/precommit.yml@main
    with:
      fake-argument: 'fake'

  release:
    needs: pre-commit
    runs-on: ubuntu-latest
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Install dependencies
        run: |
          git config --global user.email "mariosk@gmail.com"
          git config --global user.name "Marios Karagiannopoulos"
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r requirements-dev.txt  # Adjust based on your project
          npm install -g github-changelog-generator

      - name: Generate Changelog and Upload new release
        run: |
          github_changelog_generator
          git add CHANGELOG.md
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Auto-generated changelog"
          git push
          NEW_VERSION=$(git describe --abbrev=0 --tags) INSTALLATION_PATH=./tmp invoke upload-to-github

      # - name: Bump version and create release
      #   run: |
      #     pip install bump2version
      #     NEW_VERSION=$(cat CHANGELOG.md | grep "\- Release" | cut -d' ' -f3 | cut -d'v' -f2 | head -1)
      #     PART=$(cat CHANGELOG.md | grep "\- part" | cut -d' ' -f3 | head -1)
      #     bump2version --new-version ${NEW_VERSION} ${PART} --config-file bumpversion.cfg
      #     git push --follow-tags
      #     git push origin --tags
      #     NEW_VERSION=${NEW_VERSION} INSTALLATION_PATH=./tmp invoke upload-to-github
