name: Release

on:
  push:
    paths:
      - 'CHANGELOG.md'  # Adjust the path to match your specific file or directory
    branches:
      - main
      - feature/create_releases

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check commit message
      run: |
        commit_message=$(git log -1 --pretty=%B)
        if [[ $commit_message == *"[RELEASE]"* ]]; then
          echo "Release commit detected. Running release workflow."
        else
          echo "No release commit detected. Skipping release workflow."
          exit 0
        fi

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Change this to your Python version

    - name: Install dependencies
      run: |
        git config --global user.email "mariosk@gmail.com"
        git config --global user.name "Marios Karagiannopoulos"
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt.x86_64  # Adjust based on your project

    - name: Bump version and create release
      run: |
        pip install bump2version
        NEW_VERSION=$(cat CHANGELOG.md | grep "\- version" | cut -d' ' -f3)
        PART=$(cat CHANGELOG.md | grep "\- part" | cut -d' ' -f3)
        bump2version --new-version ${NEW_VERSION} ${PART}
        git push --follow-tags
        git push origin --tags

    - name: Build distributions
      run: python setup.py sdist bdist_wheel

    - name: Install twine
      run: pip install twine

    - name: Upload to PyPI
      run: twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
