name: Release

on:
  push:
    paths:
      - 'CHANGELOG.md'

jobs:
  common-steps:
    uses: gardenifi/raspirri_server/.github/workflows/common-steps.yml@main
    with:
      fake-argument: 'fake'

  release:
    needs: common-steps
    runs-on: ubuntu-latest
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Install dependencies
        run: |
          git config --global user.email "mariosk@gmail.com"
          git config --global user.name "Marios Karagiannopoulos"
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt.x86_64  # Adjust based on your project

      - name: Bump version and create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
              Describe the changes included in this release.
          draft: false
          prerelease: false
          # run: |
        #   pip install bump2version
        #   NEW_VERSION=$(cat CHANGELOG.md | grep "\- Release" | cut -d' ' -f3 | cut -d'v' -f2 | head -1)
        #   PART=$(cat CHANGELOG.md | grep "\- part" | cut -d' ' -f3 | head -1)
        #   bump2version --new-version ${NEW_VERSION} ${PART}
        #   git push --follow-tags
        #   git push origin --tags
        #   NEW_VERSION=${NEW_VERSION} INSTALLATION_PATH=./tmp invoke upload-to-github
