name: Release

on:
  push:
    paths:
      - 'CHANGELOG.md'  # Adjust the path to match your specific file or directory
    branches:
      - main
      - feature/create_releases

jobs:
  common-steps:
    uses: gardenifi/raspirri_server/.github/workflows/common-steps.yml@feature/create_releases
    with:
      fake-argument: 'fake'

  release:
    needs: common-steps
    runs-on: ubuntu-latest
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check commit message
        run: |
          commit_message=$(git log -1 --pretty=%B)
          if [[ $commit_message == *"[RELEASE]"* ]]; then
            echo "Release commit detected. Running release workflow."
          else
            echo "No release commit detected. Skipping release workflow."
            exit 0
          fi

      - name: Bump version and create release
        run: |
          pip install bump2version
          NEW_VERSION=$(cat CHANGELOG.md | grep "\- Release" | cut -d' ' -f3 | cut -d'v' -f2 | head -1)
          PART=$(cat CHANGELOG.md | grep "\- part" | cut -d' ' -f3 | head -1)
          bump2version --new-version ${NEW_VERSION} ${PART}
          git push --follow-tags
          git push origin --tags
          NEW_VERSION=${NEW_VERSION} INSTALLATION_PATH=./tmp invoke upload-to-github
