name: Tests

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  pre-commit:
    uses: gardenifi/raspirri_server/.github/workflows/precommit.yml@main
    with:
      fake-argument: 'fake'
