name: Tests

on:
  push:
    branches:
      - main
    tags: [] # Exclude tag pushes

jobs:
  pre-commit:
    uses: gardenifi/raspirri_server/.github/workflows/precommit.yml@main
    with:
      fake-argument: 'fake'
