name: Tests

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  common-steps:
    uses: gardenifi/raspirri_server/.github/workflows/precommit.yml@fix/update-readme
    with:
      fake-argument: 'fake'
