name: Tests

on:
  push:
    branches:
      - main
    paths:
      - 'raspirri/**'
      - '.github/workflows/**'

jobs:
  pre-commit:
    uses: gardenifi/raspirri_server/.github/workflows/precommit.yml@main
    with:
      fake-argument: 'fake'
