name: x86_64 CI

on:
  push:
    branches:
      - main
      - feature/create_releases

jobs:
  x86_64_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/common-steps.yml@v1
      # Other workflow-specific steps
