name: x86_64 CI

on:
  push:
    branches:
      - main
      - feature/create_releases

jobs:
  common-steps:
    uses: gardenifi/raspirri_server/.github/workflows/common-steps.yml@feature/create_releases
    with:
      fake-argument: 'fake'
